# Base configs
baseurl: "https://photos.pwncnc.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by PwnCNC"
subtitle: "See the world through my eyes!"
author: "Daniel Moran"
header:
 title: "Photography"
 subtitle: "by PwnCNC"
footer:
 name: "Want to see some more photos?"
 bio: "I'm the owner of PwnCNC and own many different CNC brands with various configurations.  I'm happy to take specific photos to help you out.  Let me know which ones you'd like."
 github: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/pwncnc"
  twitter: "https://www.twitter.com/pwncnc"
  instagram: "https://www.instagram.com/pwncnc"
  github: "https://www.github.com/pwncnc"
