# Base configs
baseurl: "https://photos.pwncnc.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by PwnCNC"
subtitle: "See the world through my eyes!"
author: "Daniel Moran"
header:
 title: "Photography"
 subtitle: "by PwnCNC"
footer:
 name: "Hey there, my name is Daniel"
 bio: "I'm the owner of PwnCNC... working hard to design awesome accessories for your hobby CNC."
 github: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/pwncnc"
  twitter: "https://www.twitter.com/pwncnc"
  instagram: "https://www.instagram.com/pwncnc"
  github: "https://www.github.com/pwncnc"
